---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dungeon-deployment
spec:
  template:
    spec:
      containers:
        - name: dungeon
          image: dungeon_image
          imagePullPolicy: Always
          ports:
            - containerPort: 8800
              protocol: TCP
      imagePullSecrets:
        - name: github
