apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dungeon
commonLabels:
  app: dungeon

resources:
- Deployment.yaml
- Service.yaml

configMapGenerator:
- name: database-configuration
  literals:
    - DB=dungeon
    - DB_HOST=mariadb.mariadb.svc.cluster.local:3306
    - DB_USER=dungeon

generatorOptions:
  disableNameSuffixHash: true

images:
- name: dungeon_image
  newName: docker.pkg.github.com/stopdenbus/dungeon/dungeon
  newTag: e59e066734447756ec78bb860ff45a066f97cb9d
