apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dungeon
commonLabels:
  app: dungeon

resources:
- Deployment.yaml
- Service.yaml

configMapGenerator:
- literals:
  - DB=dungeon
  - DB_HOST=mariadb.mariadb.svc.cluster.local
  - DB_PORT=30306
  - DB_USER=dungeon
  name: database-configuration

generatorOptions:
  disableNameSuffixHash: true

images:
- name: dungeon_image
  newName: docker.pkg.github.com/stopdenbus/dungeon/dungeon
  newTag: 51c09c77f58b62ed5112df15e451f3cb36ed38ca
