apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dungeon
commonLabels:
  app: dungeon

resources:
- Deployment.yaml
- Service.yaml

images:
- name: dungeon_image
  newName: docker.pkg.github.com/stopdenbus/dungeon/dungeon
  newTag: bla
