apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dungeon
commonLabels:
  app: dungeon

resources:
- Deployment.yaml
- Service.yaml

configMapGenerator:
- literals:
  - DB=dungeon
  - DB_HOST=mariadb.mariadb.svc.cluster.local:3306
  - DB_USER=dungeon
  name: database-configuration

generatorOptions:
  disableNameSuffixHash: true

images:
- name: dungeon_image
  newName: docker.pkg.github.com/stopdenbus/dungeon/dungeon
  newTag: df65d814bc6b2779e0fe2d4878c4dfa96ef55587
